services:
  video-summariser:
    image: video-summariser
    container_name: video-summariser-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7500:7500"
    env_file:
      - .env
    volumes:
      - downloads:/app/downloads
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:7500/health')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend-webserver:
    image: nginx:alpine
    container_name: video-summariser-ui
    ports:
      - "7510:80" # Exposes the frontend on port 7400 on your Debian server
    volumes:
      # Step up out of backend, go into frontend-app, mount the compiled dist
      - /home/raj-dash/projects/video_summariser/dist:/usr/share/nginx/html:ro
    restart: unless-stopped

volumes:
  downloads:
    driver: local
